"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url

ENVIRONMENT = os.getenv("DJANGO_ENV", "production")
DEBUG = ENVIRONMENT != "production"
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
load_dotenv(os.path.join(BASE_DIR, 'passwords.env'))
API_KEY = os.getenv('API_KEY')
API_SECRET = os.getenv('API_SECRET')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5jtas8j_uj6@qg!dlot=w_fnj)7=f_$!nid-^--e!!nzqo3a9!'

# SECURITY WARNING: don't run with debug turned on in production!
# Force DEBUG to True for development (override ENVIRONMENT check if needed)
DEBUG = True

ALLOWED_HOSTS = ['pinpoint-aaawo.ondigitalocean.app', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'backend' / 'templates' ],  # this is where index.html is
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


if ENVIRONMENT == "production" and os.getenv("DATABASE_URL"):
    DATABASES = {
        "default": dj_database_url.config(default=os.getenv("DATABASE_URL"))
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    BASE_DIR / 'backend' / 'static'
]

# Media files (user uploads)
# Store media files outside the project folder to avoid cluttering the repo
MEDIA_URL = '/media/'
# Option 1: Store in user's Documents folder (recommended for development)
# Uncomment the line below and adjust the path as needed
# MEDIA_ROOT = os.path.join(os.path.expanduser('~'), 'Documents', 'pinpoint_media')

# Option 2: Store in a dedicated folder on OneDrive (since you're using OneDrive)
# Uncomment and adjust if you prefer this location
MEDIA_ROOT = os.path.join(os.path.expanduser('~'), 'OneDrive', 'Desktop', 'cs347', 'pinpoint_media')

# Option 3: Keep in project folder (current - comment out if using options above)
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"
    }
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS settings for frontend-backend communication
# IMPORTANT: Make sure your frontend URL matches one of these!
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:5174",
]

CORS_ALLOW_CREDENTIALS = True
CORS_EXPOSE_HEADERS = ['Set-Cookie', 'Content-Type']

# Allow all origins in development (for easier debugging)
# Remove this in production!
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = False  # Keep False, use CORS_ALLOWED_ORIGINS instead
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Session configuration for cross-origin requests
# For localhost development, we'll use 'Lax' which should work
# If this doesn't work, try setting both frontend and backend to use the same origin (localhost or 127.0.0.1)
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_HTTPONLY = True  
SESSION_COOKIE_SECURE = False  # Must be False for localhost (no HTTPS)
SESSION_COOKIE_AGE = 1209600  # 2 weeks (14 days)
SESSION_SAVE_EVERY_REQUEST = True  # Keep session alive
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Persist after browser close
SESSION_COOKIE_DOMAIN = None  # None allows cookie for exact domain match
SESSION_COOKIE_PATH = '/'  # Available for all paths
SESSION_COOKIE_NAME = 'sessionid'  # Default session cookie name
