# Generated by Django 5.2.6 on 2025-10-09 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mytrips',
            options={'verbose_name_plural': 'My trips'},
        ),
        migrations.AddField(
            model_name='bucketlist',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bucket_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mytrips',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_trips', to=settings.AUTH_USER_MODEL),
        ),
    ]
