# Generated by Django 5.2.6 on 2025-10-09 18:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_mytrips_options_bucketlist_user_mytrips_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bnb',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='bnb',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='bucketlist',
            name='trips',
        ),
        migrations.RemoveField(
            model_name='mytrips',
            name='trips',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='plans',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='reviews',
        ),
        migrations.AddField(
            model_name='bnb',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bnbs', to='api.trip'),
        ),
        migrations.AddField(
            model_name='plan',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='api.trip'),
        ),
        migrations.AddField(
            model_name='rating',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.trip'),
        ),
        migrations.AddField(
            model_name='review',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.trip'),
        ),
        migrations.AddField(
            model_name='trip',
            name='bucket_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='api.bucketlist'),
        ),
        migrations.AddField(
            model_name='trip',
            name='my_trips',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='api.mytrips'),
        ),
        migrations.AlterField(
            model_name='bucketlist',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bucket_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mytrips',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_ratings', to='api.rating'),
        ),
    ]
