# Generated by Django 5.2.6 on 2025-10-09 19:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_bnb_rating_remove_bnb_reviews_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='availability',
        ),
        migrations.AddField(
            model_name='trip',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
