# Generated by Django 5.2.6 on 2025-10-10 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_trip_availability_trip_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='review',
            name='trip',
        ),
        migrations.AddField(
            model_name='rating',
            name='bnb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.bnb'),
        ),
        migrations.AddField(
            model_name='review',
            name='bnb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.bnb'),
        ),
    ]
