# Generated by Django 5.2.6 on 2025-10-13 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_rating_trip_remove_review_trip_rating_bnb_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='bucket_list',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='my_trips',
        ),
        migrations.AddField(
            model_name='bucketlist',
            name='trips',
            field=models.ManyToManyField(blank=True, related_name='bucketlists', to='api.trip'),
        ),
        migrations.AddField(
            model_name='mytrips',
            name='trips',
            field=models.ManyToManyField(blank=True, related_name='mytrips', to='api.trip'),
        ),
        migrations.AddField(
            model_name='plan',
            name='name',
            field=models.CharField(default='Unnamed Plan', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='name',
            field=models.CharField(default='Unnamed Trip', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bnb',
            name='trip',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bnbs', to='api.trip'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='activity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateField(),
        ),
    ]
