# Generated by Django 5.2.6 on 2025-10-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_trip_bucket_list_remove_trip_my_trips_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytrips',
            name='trips',
            field=models.ManyToManyField(blank=True, related_name='in_mytrips', to='api.trip'),
        ),
    ]
